In [283]:
import numpy as np

In [284]:
np.random.seed(0) # Siempre obtiene los mismos numeros aleatorios

x1 = np.random.randint(10,size=10) #Array de numeros random de longitud 10 entre 0 y 10

x2 = np.random.randint(10,size=(3,3)) #Matriz de 2D 3x3 de numeros random entre 0 y 10

x3 = np.random.randint(10,size=(3,4,5)) #Matriz de 3D 3x4x5 de numeros random entre 0 y 10

In [285]:
print(x1)
print("")
print(x2)
print("")
print(x3)

[5 0 3 3 7 9 3 5 2 4]

[[7 6 8]
 [8 1 6]
 [7 7 8]]

[[[1 5 9 8 9]
  [4 3 0 3 5]
  [0 2 3 8 1]
  [3 3 3 7 0]]

 [[1 9 9 0 4]
  [7 3 2 7 2]
  [0 0 4 5 5]
  [6 8 4 1 4]]

 [[9 8 1 1 7]
  [9 9 3 6 7]
  [2 0 3 5 9]
  [4 4 6 4 4]]]


In [286]:
numeros = np.array([1,2,3,4,5])

# Indexación

numeros[1]

2

In [287]:
# Array Slicing
# x[start:stop:step]

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [288]:
# Obtiene los elementos desde la posicion 0 hasta la 5

x[0:5]

array([0, 1, 2, 3, 4])

In [289]:
# Obtiene los primeros 5 elementos

x[:5]

array([0, 1, 2, 3, 4])

In [290]:
#Obtiene los elementos desde la posición 5

x[5:]

array([5, 6, 7, 8, 9])

In [291]:
# Obtiene los elementos de la posicion #2 a la #7

x[2:7]

array([2, 3, 4, 5, 6])

In [292]:
#Obtiene los elementos de la posición 2 a la 7, de 2 en 2

x[2:7:2]

array([2, 4, 6])

In [293]:
# Revertir el arreglo

x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [294]:
pares = x[2:7:2][::-1]
pares

array([6, 4, 2])

In [295]:
#Slicing

x[7:2:-1]

array([7, 6, 5, 4, 3])

In [296]:
data = np.array([np.arange(i*5,i*5+5) for i in range(5)])
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Slicing en arreglos multidimensionales

In [297]:
# x[row][column]

data[2][1]

11

In [298]:
data[2,1]

11

In [299]:
#Obtener las primeras dos filas y 3 columnas

data[ :2 , :3 ]

array([[0, 1, 2],
       [5, 6, 7]])

In [300]:
np.random.seed(0)
random_data= np.random.randint(10,size=(10,10))

random_data

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [301]:
# Obtener los elementos de las filas 4-7 y columnas 2-8

random_data[4:7, 2:8]

array([[0, 4, 7, 3, 2, 7],
       [5, 5, 6, 8, 4, 1],
       [1, 7, 9, 9, 3, 6]])

In [302]:
# Obtener los elementos de las filas 0-5 y columnas 0-3

random_data[:5, :3]

array([[5, 0, 3],
       [7, 6, 8],
       [5, 9, 8],
       [2, 3, 8],
       [9, 9, 0]])

In [303]:
# Obtener los elementos de as ultimas 3 filas y ultimas 5 columnas

random_data[7:, 5:]

array([[4, 6, 4, 4, 3],
       [7, 5, 5, 0, 1],
       [0, 1, 2, 4, 2]])

In [304]:
# Copiar los datos de manera incorrecta, aqui los cambios realizados tambien se reflejan en el array original

no_copy = random_data[-3:,-5:]
no_copy[0] = 50
no_copy

array([[50, 50, 50, 50, 50],
       [ 7,  5,  5,  0,  1],
       [ 0,  1,  2,  4,  2]])

In [305]:
# Copiar datos de manera correcta

copiaData = random_data[-3:,-5:].copy()
copiaData[1] = 100

In [306]:
copiaData

array([[ 50,  50,  50,  50,  50],
       [100, 100, 100, 100, 100],
       [  0,   1,   2,   4,   2]])

In [307]:
random_data

array([[ 5,  0,  3,  3,  7,  9,  3,  5,  2,  4],
       [ 7,  6,  8,  8,  1,  6,  7,  7,  8,  1],
       [ 5,  9,  8,  9,  4,  3,  0,  3,  5,  0],
       [ 2,  3,  8,  1,  3,  3,  3,  7,  0,  1],
       [ 9,  9,  0,  4,  7,  3,  2,  7,  2,  0],
       [ 0,  4,  5,  5,  6,  8,  4,  1,  4,  9],
       [ 8,  1,  1,  7,  9,  9,  3,  6,  7,  2],
       [ 0,  3,  5,  9,  4, 50, 50, 50, 50, 50],
       [ 4,  4,  8,  4,  3,  7,  5,  5,  0,  1],
       [ 5,  9,  3,  0,  5,  0,  1,  2,  4,  2]])

In [308]:
#Unir/concatenar 2 arrays

x = np.array([1,2,3])
y = np.array([3,2,1])

np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [309]:
# Uniendo matrices, las matrices se unen de manera vertical

m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[1,2,3],[4,5,6]])

m3 = np.concatenate([m1,m2],axis=0)
m3

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [310]:
# Uniendo matrices, las matrices se unen de manera horizontal

m4 = np.concatenate([m1, m2], axis=1)
m4

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [311]:
# Otra forma de concaternar de manera vertical (Conctenar por filas)

np.r_[m1,m2]

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [312]:
# Otra forma de concaternar de manera horizontal (Conctenar por columnas)

np.c_[m1,m2]

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [313]:
# Hacer un split (división) de los datos y asignarlos a variables
# np.split(array_original/lista, [end_first_split, end_second_split,...])

x = np.array([1,2,3,10,11,12,20,21,22])

x1,x2,x3 = np.split(x,[3,6])

print(x1)
print(x2)
print(x3)

[1 2 3]
[10 11 12]
[20 21 22]


In [314]:
# Redimensionar una matriz o array a una nueva dimensión
# np.reshape((new_row, new_column))

matriz = np.array(x).reshape((3,3))
matriz

array([[ 1,  2,  3],
       [10, 11, 12],
       [20, 21, 22]])

In [315]:
# Hacer un split (división) a una matriz de manera horizontal (columnas)
# np.hsplit(originall_matrix, number_of_columns)

upper,lower = np.hsplit(matriz,[2])

print(upper, end = "\n\n")
print(lower)

[[ 1  2]
 [10 11]
 [20 21]]

[[ 3]
 [12]
 [22]]


In [316]:
# Hacer un split (división) a una matriz de manera vertical (filas)
# np.vsplit(originall_matrix, number_of_rows)

upper,lower = np.vsplit(matriz,[2])

print(upper, end = "\n\n")
print(lower)

[[ 1  2  3]
 [10 11 12]]

[[20 21 22]]


#### Ufunctions/Universal functions/Funciones Universales

In [317]:
# Conjunto de datos

valores = np.random.randint(1, 100, size = 100, dtype=int)
valores

array([49, 94,  4, 99, 43, 78, 22, 74,  1, 11, 44, 59, 24, 60,  3, 99, 63,
       36, 95, 68, 83, 47, 21, 82, 51, 28, 15, 42, 59, 66, 37, 11, 87, 44,
       12,  3, 52, 81, 33, 55,  1, 39, 20, 47, 43, 57, 61, 78, 31, 25,  3,
        4, 95, 99, 14, 41, 73, 20, 96, 73, 27, 67, 53, 68, 62, 15, 97,  5,
       68, 12, 87, 78, 76, 57, 17, 25, 30, 22, 26, 81, 61, 62, 84, 34, 33,
       71, 86, 32, 14, 72, 57, 25, 80, 42, 19, 41, 55, 80, 12, 39])

In [318]:
import time

# Método con Python

def reduce_10_percent(data):
    result = []
    for i in data:
        value = i * 0.9
        result.append(value)
    
    return result

reduce_10_percent(valores)

[44.1,
 84.60000000000001,
 3.6,
 89.10000000000001,
 38.7,
 70.2,
 19.8,
 66.60000000000001,
 0.9,
 9.9,
 39.6,
 53.1,
 21.6,
 54.0,
 2.7,
 89.10000000000001,
 56.7,
 32.4,
 85.5,
 61.2,
 74.7,
 42.300000000000004,
 18.900000000000002,
 73.8,
 45.9,
 25.2,
 13.5,
 37.800000000000004,
 53.1,
 59.4,
 33.300000000000004,
 9.9,
 78.3,
 39.6,
 10.8,
 2.7,
 46.800000000000004,
 72.9,
 29.7,
 49.5,
 0.9,
 35.1,
 18.0,
 42.300000000000004,
 38.7,
 51.300000000000004,
 54.9,
 70.2,
 27.900000000000002,
 22.5,
 2.7,
 3.6,
 85.5,
 89.10000000000001,
 12.6,
 36.9,
 65.7,
 18.0,
 86.4,
 65.7,
 24.3,
 60.300000000000004,
 47.7,
 61.2,
 55.800000000000004,
 13.5,
 87.3,
 4.5,
 61.2,
 10.8,
 78.3,
 70.2,
 68.4,
 51.300000000000004,
 15.3,
 22.5,
 27.0,
 19.8,
 23.400000000000002,
 72.9,
 54.9,
 55.800000000000004,
 75.60000000000001,
 30.6,
 29.7,
 63.9,
 77.4,
 28.8,
 12.6,
 64.8,
 51.300000000000004,
 22.5,
 72.0,
 37.800000000000004,
 17.1,
 36.9,
 49.5,
 72.0,
 10.8,
 35.1]

In [319]:
%timeit (reduce_10_percent(valores))

265 µs ± 1.93 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [320]:
# Método con funciones universales

valores * 0.9

array([44.1, 84.6,  3.6, 89.1, 38.7, 70.2, 19.8, 66.6,  0.9,  9.9, 39.6,
       53.1, 21.6, 54. ,  2.7, 89.1, 56.7, 32.4, 85.5, 61.2, 74.7, 42.3,
       18.9, 73.8, 45.9, 25.2, 13.5, 37.8, 53.1, 59.4, 33.3,  9.9, 78.3,
       39.6, 10.8,  2.7, 46.8, 72.9, 29.7, 49.5,  0.9, 35.1, 18. , 42.3,
       38.7, 51.3, 54.9, 70.2, 27.9, 22.5,  2.7,  3.6, 85.5, 89.1, 12.6,
       36.9, 65.7, 18. , 86.4, 65.7, 24.3, 60.3, 47.7, 61.2, 55.8, 13.5,
       87.3,  4.5, 61.2, 10.8, 78.3, 70.2, 68.4, 51.3, 15.3, 22.5, 27. ,
       19.8, 23.4, 72.9, 54.9, 55.8, 75.6, 30.6, 29.7, 63.9, 77.4, 28.8,
       12.6, 64.8, 51.3, 22.5, 72. , 37.8, 17.1, 36.9, 49.5, 72. , 10.8,
       35.1])

In [321]:
%timeit (valores * 0.9)

1.8 µs ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [322]:
x = np.arange(4, dtype = float)
x

array([0., 1., 2., 3.])

In [323]:
# Sumar un valor a cada elemento del array

x + 2

array([2., 3., 4., 5.])

In [324]:
# Restar un valor a cada elemento del array

x - 2

array([-2., -1.,  0.,  1.])

In [325]:
# Multiplicar un valor a cada elemento del array

x * 2

array([0., 2., 4., 6.])

In [326]:
# Dividir un valor a cada elemento del array

x / 2

array([0. , 0.5, 1. , 1.5])

In [327]:
# Cambiar de signo a cada elemento del array

-x

array([-0., -1., -2., -3.])

In [330]:
fx = (x**2) + 54.6
fx

array([54.6, 55.6, 58.6, 63.6])